export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';

export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const FETCH_INGREDIENTS_FAIL = 'FETCH_INGREDIENTS_FAIL';


// order
export const PURCHASE_SANDWICH_START = 'PURCHASE_SANDWICH_START';
export const PURCHASE_SANDWICH_SUCCESS = 'PURCHASE_SANDWICH_SUCCESS';
export const PURCHASE_SANDWICH_FAIL = 'PURCHASE_SANDWICH_FAIL';


//redicting once the user clicks order
export const PURCHASE_REDIRECT_AFTER_CLICKING_ORDER = 'PURCHASE_REDIRECT_AFTER_CLICKING_ORDER';

// fetching orders from backend
export const FETCH_ORDERS_START = 'FETCH_ORDERS_START';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAIL = 'FETCH_ORDERS_FAIL';
export const FETCH_ORDERS = 'FETCH_ORDERS';

// Authenticate
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_CHECK_TIMEOUT = 'AUTH_CHECK_TIMEOUT';

export const AUTH_LOGOUT = 'AUTH_LOGOUT';
// export const AUTH_INITIATE_LOGOUT = 'AUTH_INITIATE_LOGOUT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';
